# Necessary replacement for #[AsController] syntax for PHP 7.x
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
